name: index-update
on:
  workflow_dispatch:
    inputs:
      version-tag:
        description: 'version tag'
        required: false
  # schedule:
  #   - cron: '15 5,23 * * *'

jobs:
  release-worker:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      ___X_CMD_GHACTION_X: x7
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      QYWX_BOT_RELEASE_WEBHOOK: ${{ secrets.QYWX_BOT_RELEASE_WEBHOOK }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY_FOR_SYNC }}
      INPUTS_VERSION_TAG: ${{ github.event.inputs.version-tag }}
      git_user: l
      git_email: l@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: x ws update-x-cmd-version-release


